name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Debug secrets
      run: |
        echo "HOST: ${{ secrets.SERVER_HOST }}"
        echo "PORT: ${{ secrets.SERVER_PORT }}"
        echo "USER: ${{ secrets.SERVER_USERNAME }}"
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 120s
        script: |
          cd /home/frontend/over101/game_frontend
          git pull origin main
          npm ci
          npm run build
          pm2 restart game_frontend
          echo "Deployment completed at $(date)" >> /home/frontend/over101/game_frontend/deployment.log

    - name: Notify deployment status (optional)
      if: always()
      run: |
        echo "Deployment finished with status: ${{ job.status }}"