name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 120s
        script: |
          cd /home/frontend/over101/game_frontend
          git pull origin main
          npm ci
          npm run build
          
          # 기존 game-frontend 프로세스가 있으면 삭제
          pm2 delete game-frontend 2>/dev/null || echo "No existing game-frontend process found"
          
          # 새로운 프로세스 시작
          pm2 start serve --name "game-frontend" -- -s dist -l 5173
          
          # pm2 설정 저장 (재부팅 시 자동 시작을 위해)
          pm2 save
          
          echo "Deployment completed at $(date)" >> /home/frontend/over101/game_frontend/deployment.log

    - name: Notify deployment status
      if: always()
      run: |
        echo "Deployment finished with status: ${{ job.status }}"