name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 120s
        script: |
          cd /home/frontend/over101/game_frontend
          
          # nvm 로드 및 Node.js 22 활성화
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 22
          
          if ! git pull origin main; then
            echo "Git pull failed"
            exit 1
          fi
          
          if ! npm ci; then
            echo "npm ci failed"
            exit 1
          fi
          
          if ! npm run build; then
            echo "Build failed"
            exit 1
          fi
          
          pm2 delete game-frontend 2>/dev/null || echo "No existing process"
          
          if ! command -v serve &> /dev/null; then
            npm install -g serve
          fi
          
          pm2 start serve --name "game-frontend" -- -s dist -l 5173
          pm2 save
          
          echo "Deployment completed successfully at $(date)" >> deployment.log